### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#143]
Main task to track some things we discussed that we should do before getting to 1.0: 

- [x] #115 Write a document for converting a create-react-app repository/project into a modular repository.
- [ ] #58 the default app template shouldn't look like the CRA default view
- [ ] #144 Generate nicer READMEs inside new projects/apps/views/packages. 
- [x] #110 What does the modular upgrade experience look and feel like? 
- [x] #253 Library builds: Umbrella issue 
- [ ] #48 E2E tests
- [x] #147 affected builds 
- [x] #60 export modular.tsconfig ([PR](https://github.com/jpmorganchase/modular/pull/142), [PR](https://github.com/jpmorganchase/modular/pull/219)) 
- [x] #169 Fix tests, but actually this time. ([PR](https://github.com/jpmorganchase/modular/issues/169)) 
- [x] #128 update to create-react-app 4.0 ([PR](https://github.com/jpmorganchase/modular/pull/132))
- [x] #59 export modular-views.macro ([PR](https://github.com/jpmorganchase/modular/pull/140))
- [x] #42 Fix `package.json` in `eslint-config-modular-app` ([PR](https://github.com/jpmorganchase/modular/pull/175))
- [x] #133 modular should tell you when it's out-of-date ([PR](https://github.com/jpmorganchase/modular/pull/203))
- [x] #68 add .editorconfig to generated repos ([PR](https://github.com/jpmorganchase/modular/pull/199))
- [x] #49 modular for libs  ([PR](https://github.com/jpmorganchase/modular/pull/195))
- [x] #136 enable in-browser linting experience ([PR](https://github.com/jpmorganchase/modular/pull/179))
- [x] #130 modular test script does not run sub-package test ([PR](https://github.com/jpmorganchase/modular/pull/141))
- [x] #149 react/react-dom (and other core dependencies) should be installed at the root ([PR](https://github.com/jpmorganchase/modular/pull/167))
- [x] #151 Freshly generated project has broken test on Windows ([PR](https://github.com/jpmorganchase/modular/pull/154))
- [x] #156 creating a new view/package doesn't replace the stub names with the new view/package name ([PR](https://github.com/jpmorganchase/modular/pull/167))

--- 

Further, there's a discussion to be had about a website and examples, but we'll get to that as well.

**Comment by matt-d-webb** [comment]
@threepointone Thank you for this consolidated list.
