### ISSUE TITLE
Fix tests, but actually this time. 

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#169]
Our tests behave a little funnily. They got a little better after we moved to a self hosted model, but there are still some rough edges. 

- [x] Run `yarn test`. Wait for a few seconds, then hit ctrl-c to end it. You'll notice that it still runs in the background, creating the sample repos/apps/projects/whatever, all the way to completion. That's weird.  (Fixed in https://github.com/jpmorganchase/modular/issues/169)

- [x] We have the test that starts up the dev server disabled right now https://github.com/jpmorganchase/modular/blob/09b638ad29e81b786465a210b508ee18af67709b/packages/modular-scripts/src/__tests__/index.test.ts#L195 This is because when you run it, and it ends, you'll see that it leaves hanging node process in the background, i.e.: In activity monitor, you'll see the `node` processes still running, and you'll have to kill them manually. This doesn't happen in production, so it's super weird. (Fixed in https://github.com/jpmorganchase/modular/issues/169, enabled in https://github.com/jpmorganchase/modular/pull/189) 

- [x] We have the test that runs tests (meta hehe) disabled right now too https://github.com/jpmorganchase/modular/blob/09b638ad29e81b786465a210b508ee18af67709b/packages/modular-scripts/src/__tests__/index.test.ts#L272 The problem here is that the output of running the tests gives the 'coloured' strings, which it shouldn't when CI: true is passed as an environment variable. So I worked around that by stripping the characters with a regex that up, but the whitespace still appears to be different, leading the out put to *slightly* be different locally/in CI. The correct fix here is probably to generate the text properly in the first place. (Fixed in https://github.com/jpmorganchase/modular/issues/169)

- [x] @Cono52 mentioned that the tests don't pass correctly in windows at all. So that's something else to look into. (Fixed in https://github.com/jpmorganchase/modular/issues/169)

- [x] @Cono52 further mentioned that they don't run inside docker. This isn't super critical since we don't use that workflow anymore, but would be good to investigate why. (Deprioritised since we don't use docker for tests anymore)

**Comment by threepointone** [comment]
My initial guess is that `execa` is kinda buggy, so maybe we can experiment replacing it with something like `cross-spawn` for shelling out. Unsure.

**Comment by threepointone** [comment]
https://github.com/jpmorganchase/modular/issues/169 actually did fix most of these, thanks a bunch @Cono52, that was dope. Closing this issue.
