### ISSUE TITLE
Library builds: Umbrella issue

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#253]
Using this issue to track stuff remaining todo for library builds with modular

- [ ] generate dev/prod builds, and support `__DEV__` #229
- [ ] support multiple entrypoints for libs #228
- [ ] parity between features for libs and apps #227
- [ ] use it ourselves, and write docs #202 
- [ ] rebuilding affected packages/apps. #147
